name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install `just` command runner
        uses: extractions/setup-just@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          # Do not install the `rust-src` component that is defined in the
          # rust-toolchain.toml file, as it is needed only by rust-analyzer.
          components:

      - name: Compile project
        run: just build-release

      - name: List binaries
        run: ls -lah ./target/release/

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            target/release/sail
            target/release/saild
