name: release
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile project
        run: cargo build --release

      - name: Prepare upload folder
        run: |
          mkdir files
          mv -t files target/release/sail target/release/saild
          mv -t files support/systemd/sail.service support/systemd/sail.socket

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: sail-release
          path: files
