name: release
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile project
        run: cargo build --release

      - name: Prepare upload folder
        run: |
          mkdir sail
          cp target/release/sail sail/
          cp target/release/saild sail/
          cp support/systemd/sail.service sail/
          cp support/systemd/sail.socket sail/
          tar -czvf sail-${{ github.ref_name }}.tar.gz -C sail .

      - name: Upload binaries
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          makeLatest: true
          artifacts: sail-${{ github.ref_name }}.tar.gz
